In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_performance_assign3.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,some high school,standard,completed,89,62,71
1,male,group B,some college,free/reduced,none,53,51,80
2,female,group D,high school,free/reduced,none,63,47,68
3,female,group B,associate's degree,free/reduced,completed,57,71,71
4,female,group B,some college,free/reduced,none,88,84,80

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       100 non-null    object
 1   race/ethnicity               100 non-null    object
 2   parental level of education  100 non-null    object
 3   lunch                        100 non-null    object
 4   test preparation course      100 non-null    object
 5   math score                   100 non-null    int64
 6   reading score                100 non-null    int64
 7   writing score                100 non-null    int64
dtypes: int64(3), object(5)
memory usage: 6.4+ KB

In [7]:
df.describe()

       math score  reading score  writing score
count  100.000000       100.0000      100.00000
mean    66.130000        67.8400       69.43000
std     14.680197        14.4122       16.62252
min     33.000000        21.0000       33.00000
25%     56.000000        59.0000       59.50000
50%     65.000000        66.5000       71.00000
75%     73.500000        78.0000       79.00000
max    100.000000       100.0000      100.00000

In [21]:
df.groupby("gender")[["math score", "reading score", "writing score"]].agg(
    ["mean", "median", "std", "min", "max"]
)

       math score                            reading score                    \
             mean median        std min  max          mean median        std
gender
female  67.568182   65.0  14.384096  36   95     66.250000   64.0  13.966946
male    65.000000   65.0  14.939880  33  100     69.089286   69.0  14.756542

                writing score
       min  max          mean median        std min  max
gender
female  34   92     71.409091   71.0  15.423205  37  100
male    21  100     67.875000   68.0  17.486683  33  100

In [23]:
grouped=df.groupby("gender")[["math score", "reading score", "writing score"]].agg(
    ["mean", "median", "std", "min", "max"]
)

In [25]:
score_list = grouped.apply(list)
print(score_list)

       math score                            reading score                    \
             mean median        std min  max          mean median        std
gender
female  67.568182   65.0  14.384096  36   95     66.250000   64.0  13.966946
male    65.000000   65.0  14.939880  33  100     69.089286   69.0  14.756542

                writing score
       min  max          mean median        std min  max
gender
female  34   92     71.409091   71.0  15.423205  37  100
male    21  100     67.875000   68.0  17.486683  33  100

In [27]:
df.groupby("lunch")["reading score"].agg(
    Mean="mean",
    Median="median",
    Min="min",
    Max="max",
    Std="std"
)

                   Mean  Median  Min  Max        Std
lunch
free/reduced  66.924528    63.0   21   96  16.119564
standard      68.872340    69.0   37  100  12.298139

In [29]:
df.groupby("race/ethnicity")[["math score", "reading score", "writing score"]].agg(
    ["min", "max"]
)

               math score      reading score      writing score
                      min  max           min  max           min  max
race/ethnicity
group A                43   95            21  100            37  100
group B                41   89            37   88            47   96
group C                33   94            34   89            33   97
group D                41  100            47   92            36   98
group E                45   98            43   92            37  100